version: '3'
services:

  mongodb-primary:
    image: mongo-repl-local:v1.0
    container_name: mongodb-primary
    hostname: mongodb-primary
    command: --port 27011
    volumes:
      # データの永続化
      - ./mongo/data/primary:/data/db
      # 初期化スクリプトの配置
      - ./mongo/etc/script:/script
    expose:
    - 27011
    ports:
      - 27011:27011
    networks:
      mynet:
        ipv4_address: 192.168.1.2
    restart: always

  mongodb-secondary:
    image: mongo-repl-local:v1.0
    container_name: mongodb-secondary
    hostname: mongodb-secondary
    command: --port 27012
    volumes:
      # データの永続化
      - ./mongo/data/secondary:/data/db
    expose:
    - 27012
    ports:
      - 27012:27012
    networks:
      mynet:
        ipv4_address: 192.168.1.3
    restart: always

  mongodb-arbiter:
    image: mongo-repl-local:v1.0
    container_name: mongodb-arbiter
    hostname: mongodb-arbiter
    command: --port 27013
    volumes:
      # データの永続化
      - ./mongo/data/arbiter:/data/db
    expose:
    - 27013
    ports:
      - 27013:27013
    networks:
      mynet:
        ipv4_address: 192.168.1.4
    restart: always
  
  redis-master:
    image: redis:6.2.6
    container_name: redis-master
    hostname: redis-master
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-master.conf /redis/redis.conf;
        redis-server /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-master.conf:/conf/redis-master.conf
    expose:
    - 6381
    ports:
      - 6381:6381
    networks:
      mynet:
        ipv4_address: 192.168.1.5
    restart: always
  
  redis-slave-1:
    image: redis:6.2.6
    container_name: redis-slave-1
    hostname: redis-slave-1
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-slave.conf /redis/redis.conf;
        redis-server /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-slave.conf:/conf/redis-slave.conf
    expose:
    - 6381
    ports:
      - 6382:6381
    networks:
      mynet:
        ipv4_address: 192.168.1.6
    restart: always
  
  redis-slave-2:
    image: redis:6.2.6
    container_name: redis-slave-2
    hostname: redis-slave-2
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-slave.conf /redis/redis.conf;
        redis-server /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-slave.conf:/conf/redis-slave.conf
    expose:
    - 6381
    ports:
      - 6383:6381
    networks:
      mynet:
        ipv4_address: 192.168.1.7
    restart: always
  
  redis-sentinel-1:
    image: redis:6.2.6
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-sentinel.conf /redis/redis.conf;
        redis-sentinel /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-sentinel.conf:/conf/redis-sentinel.conf
    expose:
    - 26381
    ports:
      - 26381:26381
    networks:
      mynet:
        ipv4_address: 192.168.1.8
    restart: always
  
  redis-sentinel-2:
    image: redis:6.2.6
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-sentinel.conf /redis/redis.conf;
        redis-sentinel /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-sentinel.conf:/conf/redis-sentinel.conf
    expose:
    - 26381
    ports:
      - 26382:26381
    networks:
      mynet:
        ipv4_address: 192.168.1.9
    restart: always
  
  redis-sentinel-3:
    image: redis:6.2.6
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    command:
      - /bin/sh
      - -c
      - >
        mkdir /redis;
        cp /conf/redis-sentinel.conf /redis/redis.conf;
        redis-sentinel /redis/redis.conf;
    volumes:
      - ./redis/conf/redis-sentinel.conf:/conf/redis-sentinel.conf
    expose:
    - 26381
    ports:
      - 26383:26381
    networks:
      mynet:
        ipv4_address: 192.168.1.10
    restart: always

networks:
  mynet:
    ipam:
      config:
      - subnet: 192.168.1.0/24
