use altair
db.createCollection('users')
db.createCollection('projects')
db.createCollection('project_histories')
db.createCollection('tickets')
db.createCollection('entry_members')
db.createCollection('ticket_watchers')
db.createCollection('lives')
db.createCollection('ticket_histories')
db.createCollection('entry_member_histories')
db.createCollection('ticket_watcher_histories')
db.createCollection('live_histories')
db.createCollection('ticket_comments')
db.createCollection('clans')
db.createCollection('members')
db.createCollection('member_invites')
db.createCollection('member_invite_histories')
db.createCollection('game_titles')
db.createCollection('play_titles')
db.createCollection('member_templates')
db.createCollection('template_members')
db.createCollection('admissions')
db.createCollection('project_watchers')
db.createCollection('project_watcher_histories')
db.createCollection('federated_credentials')
db.createCollection('providers')
db.providers.insert( { name:'https://accounts.google.com' } )